"""Generate web/fallback-data.js — bundled sample data for the front-end's offline/preview mode.

Bundles the ruleset payloads (labels + ability rules + SRD-derived option lists, exactly the
GET /ruleset/<slug> shape) and a few sample characters, so the prototype's dropdowns and
starter rail populate even when the Flask bridge isn't reachable. Portrait imageUrls are nulled
(they point at localhost and would 404 offline → the front-end shows its drop-slot instead).

Run:  python scripts/build_fallback.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from forge.ruleset import Ruleset  # noqa: E402

RULESET_SLUGS = ["dnd5e-2014", "dnd5e-2024", "homebrew-grimdark"]
SAMPLE_FILES = ["hane.json", "sample_pc.json", "live_brakkin-ironeye.json"]


def ruleset_payload(slug: str) -> dict:
    rs = Ruleset(slug)
    return {
        "slug": rs.slug, "label": rs.label, "labels": rs.labels,
        "abilityRules": rs.ability_rules, "statblock": rs.statblock,
        "optionLists": rs.option_lists(),
    }


def main() -> int:
    rulesets = {slug: ruleset_payload(slug) for slug in RULESET_SLUGS}

    characters = []
    for f in SAMPLE_FILES:
        p = REPO / "samples" / f
        if not p.exists():
            continue
        c = json.loads(p.read_text(encoding="utf-8"))
        for slot in (c.get("portraits") or {}).values():  # null offline-unreachable image URLs
            slot["imageUrl"] = None
        characters.append(c)

    data = {"defaultRuleset": "dnd5e-2014", "rulesets": rulesets, "characters": characters}
    out = REPO / "web" / "fallback-data.js"
    out.parent.mkdir(exist_ok=True)
    out.write_text(
        "// Auto-generated by scripts/build_fallback.py — bundled sample data for offline/preview mode.\n"
        "window.FORGE_FALLBACK = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {out}: {len(characters)} characters, {len(rulesets)} rulesets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
