// Auto-generated by scripts/build_fallback.py — bundled sample data for offline/preview mode.
window.FORGE_FALLBACK = {
  "defaultRuleset": "dnd5e-2014",
  "rulesets": {
    "dnd5e-2014": {
      "slug": "dnd5e-2014",
      "label": "D&D 5e (2014)",
      "labels": {
        "species": "Race",
        "subspecies": "Subrace"
      },
      "abilityRules": {
        "asiSource": "species",
        "pointBuyBudget": 27,
        "pointBuyRange": [
          8,
          15
        ],
        "standardArray": [
          15,
          14,
          13,
          12,
          10,
          8
        ],
        "monsterBounds": [
          1,
          30
        ]
      },
      "statblock": {
        "showInitiativeLine": false,
        "fieldOrder": [
          "ac",
          "hp",
          "speed",
          "saves",
          "skills",
          "resist",
          "condImm",
          "senses",
          "languages",
          "challenge"
        ]
      },
      "optionLists": {
        "classes": [
          {
            "index": "barbarian",
            "name": "Barbarian"
          },
          {
            "index": "bard",
            "name": "Bard"
          },
          {
            "index": "cleric",
            "name": "Cleric"
          },
          {
            "index": "druid",
            "name": "Druid"
          },
          {
            "index": "fighter",
            "name": "Fighter"
          },
          {
            "index": "monk",
            "name": "Monk"
          },
          {
            "index": "paladin",
            "name": "Paladin"
          },
          {
            "index": "ranger",
            "name": "Ranger"
          },
          {
            "index": "rogue",
            "name": "Rogue"
          },
          {
            "index": "sorcerer",
            "name": "Sorcerer"
          },
          {
            "index": "warlock",
            "name": "Warlock"
          },
          {
            "index": "wizard",
            "name": "Wizard"
          }
        ],
        "subclassesByClass": {
          "barbarian": [
            {
              "index": "berserker",
              "name": "Berserker"
            }
          ],
          "bard": [
            {
              "index": "lore",
              "name": "Lore"
            }
          ],
          "cleric": [
            {
              "index": "life",
              "name": "Life"
            }
          ],
          "druid": [
            {
              "index": "land",
              "name": "Land"
            }
          ],
          "fighter": [
            {
              "index": "champion",
              "name": "Champion"
            }
          ],
          "monk": [
            {
              "index": "open-hand",
              "name": "Open Hand"
            }
          ],
          "paladin": [
            {
              "index": "devotion",
              "name": "Devotion"
            }
          ],
          "ranger": [
            {
              "index": "hunter",
              "name": "Hunter"
            }
          ],
          "rogue": [
            {
              "index": "thief",
              "name": "Thief"
            }
          ],
          "sorcerer": [
            {
              "index": "draconic",
              "name": "Draconic"
            }
          ],
          "warlock": [
            {
              "index": "fiend",
              "name": "Fiend"
            }
          ],
          "wizard": [
            {
              "index": "evocation",
              "name": "Evocation"
            }
          ]
        },
        "species": [
          {
            "index": "dwarf",
            "name": "Dwarf"
          },
          {
            "index": "elf",
            "name": "Elf"
          },
          {
            "index": "halfling",
            "name": "Halfling"
          },
          {
            "index": "human",
            "name": "Human"
          },
          {
            "index": "dragonborn",
            "name": "Dragonborn"
          },
          {
            "index": "gnome",
            "name": "Gnome"
          },
          {
            "index": "half-elf",
            "name": "Half-Elf"
          },
          {
            "index": "half-orc",
            "name": "Half-Orc"
          },
          {
            "index": "tiefling",
            "name": "Tiefling"
          }
        ],
        "subspecies": [
          {
            "index": "hill-dwarf",
            "name": "Hill Dwarf"
          },
          {
            "index": "high-elf",
            "name": "High Elf"
          },
          {
            "index": "lightfoot-halfling",
            "name": "Lightfoot Halfling"
          },
          {
            "index": "rock-gnome",
            "name": "Rock Gnome"
          }
        ],
        "backgrounds": [
          {
            "index": "acolyte",
            "name": "Acolyte"
          }
        ],
        "feats": [
          {
            "index": "grappler",
            "name": "Grappler"
          }
        ],
        "conditions": [
          {
            "index": "blinded",
            "name": "Blinded"
          },
          {
            "index": "charmed",
            "name": "Charmed"
          },
          {
            "index": "deafened",
            "name": "Deafened"
          },
          {
            "index": "frightened",
            "name": "Frightened"
          },
          {
            "index": "grappled",
            "name": "Grappled"
          },
          {
            "index": "incapacitated",
            "name": "Incapacitated"
          },
          {
            "index": "invisible",
            "name": "Invisible"
          },
          {
            "index": "paralyzed",
            "name": "Paralyzed"
          },
          {
            "index": "petrified",
            "name": "Petrified"
          },
          {
            "index": "poisoned",
            "name": "Poisoned"
          },
          {
            "index": "prone",
            "name": "Prone"
          },
          {
            "index": "restrained",
            "name": "Restrained"
          },
          {
            "index": "stunned",
            "name": "Stunned"
          },
          {
            "index": "unconscious",
            "name": "Unconscious"
          },
          {
            "index": "exhaustion",
            "name": "Exhaustion"
          }
        ],
        "creatureTypes": [
          "aberration",
          "beast",
          "celestial",
          "construct",
          "dragon",
          "elemental",
          "fey",
          "fiend",
          "giant",
          "humanoid",
          "monstrosity",
          "ooze",
          "plant",
          "undead"
        ],
        "sizes": [
          "Tiny",
          "Small",
          "Medium",
          "Large",
          "Huge",
          "Gargantuan"
        ]
      }
    },
    "dnd5e-2024": {
      "slug": "dnd5e-2024",
      "label": "D&D 5e (2024)",
      "labels": {
        "species": "Species",
        "subspecies": "Subspecies"
      },
      "abilityRules": {
        "asiSource": "background",
        "pointBuyBudget": 27,
        "pointBuyRange": [
          8,
          15
        ],
        "standardArray": [
          15,
          14,
          13,
          12,
          10,
          8
        ],
        "monsterBounds": [
          1,
          30
        ]
      },
      "statblock": {
        "showInitiativeLine": true,
        "fieldOrder": [
          "ac",
          "initiative",
          "hp",
          "speed",
          "saves",
          "skills",
          "resist",
          "condImm",
          "senses",
          "languages",
          "challenge"
        ]
      },
      "optionLists": {
        "classes": [
          {
            "index": "barbarian",
            "name": "Barbarian"
          },
          {
            "index": "bard",
            "name": "Bard"
          },
          {
            "index": "cleric",
            "name": "Cleric"
          },
          {
            "index": "druid",
            "name": "Druid"
          },
          {
            "index": "fighter",
            "name": "Fighter"
          },
          {
            "index": "monk",
            "name": "Monk"
          },
          {
            "index": "paladin",
            "name": "Paladin"
          },
          {
            "index": "ranger",
            "name": "Ranger"
          },
          {
            "index": "rogue",
            "name": "Rogue"
          },
          {
            "index": "sorcerer",
            "name": "Sorcerer"
          },
          {
            "index": "warlock",
            "name": "Warlock"
          },
          {
            "index": "wizard",
            "name": "Wizard"
          }
        ],
        "subclassesByClass": {
          "barbarian": [
            {
              "index": "path-of-the-berserker",
              "name": "Path of the Berserker"
            }
          ],
          "bard": [
            {
              "index": "college-of-lore",
              "name": "College of Lore"
            }
          ],
          "cleric": [
            {
              "index": "life-domain",
              "name": "Life Domain"
            }
          ],
          "druid": [
            {
              "index": "circle-of-the-land",
              "name": "Circle of the Land"
            }
          ],
          "fighter": [
            {
              "index": "champion",
              "name": "Champion"
            }
          ],
          "monk": [
            {
              "index": "warrior-of-the-open-hand",
              "name": "Warrior of the Open Hand"
            }
          ],
          "paladin": [
            {
              "index": "oath-of-devotion",
              "name": "Oath of Devotion"
            }
          ],
          "ranger": [
            {
              "index": "hunter",
              "name": "Hunter"
            }
          ],
          "rogue": [
            {
              "index": "thief",
              "name": "Thief"
            }
          ],
          "sorcerer": [
            {
              "index": "draconic-sorcery",
              "name": "Draconic Sorcery"
            }
          ],
          "warlock": [
            {
              "index": "fiend-patron",
              "name": "Fiend Patron"
            }
          ],
          "wizard": [
            {
              "index": "evoker",
              "name": "Evoker"
            }
          ]
        },
        "species": [
          {
            "index": "dragonborn",
            "name": "Dragonborn"
          },
          {
            "index": "dwarf",
            "name": "Dwarf"
          },
          {
            "index": "elf",
            "name": "Elf"
          },
          {
            "index": "gnome",
            "name": "Gnome"
          },
          {
            "index": "goliath",
            "name": "Goliath"
          },
          {
            "index": "halfling",
            "name": "Halfling"
          },
          {
            "index": "human",
            "name": "Human"
          },
          {
            "index": "orc",
            "name": "Orc"
          },
          {
            "index": "tiefling",
            "name": "Tiefling"
          }
        ],
        "subspecies": [
          {
            "index": "draconic-ancestor-black",
            "name": "Draconic Ancestor: Black"
          },
          {
            "index": "draconic-ancestor-blue",
            "name": "Draconic Ancestor: Blue"
          },
          {
            "index": "draconic-ancestor-brass",
            "name": "Draconic Ancestor: Brass"
          },
          {
            "index": "draconic-ancestor-bronze",
            "name": "Draconic Ancestor: Bronze"
          },
          {
            "index": "draconic-ancestor-copper",
            "name": "Draconic Ancestor: Copper"
          },
          {
            "index": "draconic-ancestor-gold",
            "name": "Draconic Ancestor: Gold"
          },
          {
            "index": "draconic-ancestor-green",
            "name": "Draconic Ancestor: Green"
          },
          {
            "index": "draconic-ancestor-red",
            "name": "Draconic Ancestor: Red"
          },
          {
            "index": "draconic-ancestor-silver",
            "name": "Draconic Ancestor: Silver"
          },
          {
            "index": "draconic-ancestor-white",
            "name": "Draconic Ancestor: White"
          },
          {
            "index": "elven-lineage-drow",
            "name": "Elven Lineage: Drow"
          },
          {
            "index": "elven-lineage-high-elf",
            "name": "Elven Lineage: High Elf"
          },
          {
            "index": "elven-lineage-wood-elf",
            "name": "Elven Lineage: Wood Elf"
          },
          {
            "index": "gnomish-lineage-forest-gnome",
            "name": "Gnomish Lineage: Forest Gnome"
          },
          {
            "index": "gnomish-lineage-rock-gnome",
            "name": "Gnomish Lineage: Rock Gnome"
          },
          {
            "index": "giant-ancestry-clouds-jaunt",
            "name": "Giant Ancestry: Cloud's Jaunt"
          },
          {
            "index": "giant-ancestry-fires-burn",
            "name": "Giant Ancestry: Fire's Burn"
          },
          {
            "index": "giant-ancestry-frosts-chill",
            "name": "Giant Ancestry: Frost's Chill"
          },
          {
            "index": "giant-ancestry-hills-tumble",
            "name": "Giant Ancestry: Hill's Tumble"
          },
          {
            "index": "giant-ancestry-stones-endurance",
            "name": "Giant Ancestry: Stone's Endurance"
          },
          {
            "index": "giant-ancestry-storms-thunder",
            "name": "Giant Ancestry: Storm's Thunder"
          },
          {
            "index": "fiendish-legacy-abyssal",
            "name": "Fiendish Legacy: Abyssal"
          },
          {
            "index": "fiendish-legacy-chthonic",
            "name": "Fiendish Legacy: Chthonic"
          },
          {
            "index": "fiendish-legacy-infernal",
            "name": "Fiendish Legacy: Infernal"
          }
        ],
        "backgrounds": [
          {
            "index": "acolyte",
            "name": "Acolyte"
          },
          {
            "index": "criminal",
            "name": "Criminal"
          },
          {
            "index": "sage",
            "name": "Sage"
          },
          {
            "index": "soldier",
            "name": "Soldier"
          }
        ],
        "feats": [
          {
            "index": "alert",
            "name": "Alert"
          },
          {
            "index": "magic-initiate",
            "name": "Magic Initiate"
          },
          {
            "index": "savage-attacker",
            "name": "Savage Attacker"
          },
          {
            "index": "skilled",
            "name": "Skilled"
          },
          {
            "index": "ability-score-improvement",
            "name": "Ability Score Improvement"
          },
          {
            "index": "grappler",
            "name": "Grappler"
          },
          {
            "index": "archery",
            "name": "Archery"
          },
          {
            "index": "defense",
            "name": "Defense"
          },
          {
            "index": "great-weapon-fighting",
            "name": "Great Weapon Fighting"
          },
          {
            "index": "two-weapon-fighting",
            "name": "Two Weapon Fighting"
          },
          {
            "index": "boon-of-combat-prowess",
            "name": "Boon of Combat Prowess"
          },
          {
            "index": "boon-of-dimensional-travel",
            "name": "Boon of Dimensional Travel"
          },
          {
            "index": "boon-of-fate",
            "name": "Boon of Fate"
          },
          {
            "index": "boon-of-irresistible-offense",
            "name": "Boon of Irresistible Offense"
          },
          {
            "index": "boon-of-spell-recall",
            "name": "Boon of Spell Recall"
          },
          {
            "index": "boon-of-the-night-spirit",
            "name": "Boon of the Night Spirit"
          },
          {
            "index": "boon-of-truesight",
            "name": "Boon of Truesight"
          }
        ],
        "conditions": [
          {
            "index": "blinded",
            "name": "Blinded"
          },
          {
            "index": "charmed",
            "name": "Charmed"
          },
          {
            "index": "deafened",
            "name": "Deafened"
          },
          {
            "index": "exhaustion",
            "name": "Exhaustion"
          },
          {
            "index": "frightened",
            "name": "Frightened"
          },
          {
            "index": "grappled",
            "name": "Grappled"
          },
          {
            "index": "incapacitated",
            "name": "Incapacitated"
          },
          {
            "index": "invisible",
            "name": "Invisible"
          },
          {
            "index": "paralyzed",
            "name": "Paralyzed"
          },
          {
            "index": "petrified",
            "name": "Petrified"
          },
          {
            "index": "poisoned",
            "name": "Poisoned"
          },
          {
            "index": "prone",
            "name": "Prone"
          },
          {
            "index": "restrained",
            "name": "Restrained"
          },
          {
            "index": "stunned",
            "name": "Stunned"
          },
          {
            "index": "unconscious",
            "name": "Unconscious"
          }
        ],
        "creatureTypes": [
          "aberration",
          "beast",
          "celestial",
          "construct",
          "dragon",
          "elemental",
          "fey",
          "fiend",
          "giant",
          "humanoid",
          "monstrosity",
          "ooze",
          "plant",
          "undead"
        ],
        "sizes": [
          "Tiny",
          "Small",
          "Medium",
          "Large",
          "Huge",
          "Gargantuan"
        ]
      }
    },
    "homebrew-grimdark": {
      "slug": "homebrew-grimdark",
      "label": "Grimdark (homebrew)",
      "labels": {
        "species": "Bloodline",
        "subspecies": "Subrace"
      },
      "abilityRules": {
        "asiSource": "species",
        "pointBuyBudget": 32,
        "pointBuyRange": [
          8,
          15
        ],
        "standardArray": [
          15,
          14,
          13,
          12,
          10,
          8
        ],
        "monsterBounds": [
          1,
          30
        ]
      },
      "statblock": {
        "showInitiativeLine": false,
        "fieldOrder": [
          "ac",
          "hp",
          "speed",
          "saves",
          "skills",
          "resist",
          "condImm",
          "senses",
          "languages",
          "challenge"
        ]
      },
      "optionLists": {
        "classes": [
          {
            "index": "barbarian",
            "name": "Barbarian"
          },
          {
            "index": "bard",
            "name": "Bard"
          },
          {
            "index": "cleric",
            "name": "Cleric"
          },
          {
            "index": "druid",
            "name": "Druid"
          },
          {
            "index": "fighter",
            "name": "Fighter"
          },
          {
            "index": "monk",
            "name": "Monk"
          },
          {
            "index": "paladin",
            "name": "Paladin"
          },
          {
            "index": "ranger",
            "name": "Ranger"
          },
          {
            "index": "rogue",
            "name": "Rogue"
          },
          {
            "index": "sorcerer",
            "name": "Sorcerer"
          },
          {
            "index": "warlock",
            "name": "Warlock"
          },
          {
            "index": "wizard",
            "name": "Wizard"
          }
        ],
        "subclassesByClass": {
          "barbarian": [
            {
              "index": "berserker",
              "name": "Berserker"
            }
          ],
          "bard": [
            {
              "index": "lore",
              "name": "Lore"
            }
          ],
          "cleric": [
            {
              "index": "life",
              "name": "Life"
            }
          ],
          "druid": [
            {
              "index": "land",
              "name": "Land"
            }
          ],
          "fighter": [
            {
              "index": "champion",
              "name": "Champion"
            }
          ],
          "monk": [
            {
              "index": "open-hand",
              "name": "Open Hand"
            }
          ],
          "paladin": [
            {
              "index": "devotion",
              "name": "Devotion"
            }
          ],
          "ranger": [
            {
              "index": "hunter",
              "name": "Hunter"
            }
          ],
          "rogue": [
            {
              "index": "thief",
              "name": "Thief"
            }
          ],
          "sorcerer": [
            {
              "index": "draconic",
              "name": "Draconic"
            }
          ],
          "warlock": [
            {
              "index": "fiend",
              "name": "Fiend"
            }
          ],
          "wizard": [
            {
              "index": "evocation",
              "name": "Evocation"
            }
          ]
        },
        "species": [
          {
            "index": "dwarf",
            "name": "Dwarf"
          },
          {
            "index": "elf",
            "name": "Elf"
          },
          {
            "index": "halfling",
            "name": "Halfling"
          },
          {
            "index": "human",
            "name": "Human"
          },
          {
            "index": "dragonborn",
            "name": "Dragonborn"
          },
          {
            "index": "gnome",
            "name": "Gnome"
          },
          {
            "index": "half-elf",
            "name": "Half-Elf"
          },
          {
            "index": "half-orc",
            "name": "Half-Orc"
          },
          {
            "index": "tiefling",
            "name": "Tiefling"
          }
        ],
        "subspecies": [
          {
            "index": "hill-dwarf",
            "name": "Hill Dwarf"
          },
          {
            "index": "high-elf",
            "name": "High Elf"
          },
          {
            "index": "lightfoot-halfling",
            "name": "Lightfoot Halfling"
          },
          {
            "index": "rock-gnome",
            "name": "Rock Gnome"
          }
        ],
        "backgrounds": [
          {
            "index": "acolyte",
            "name": "Acolyte"
          }
        ],
        "feats": [
          {
            "index": "grappler",
            "name": "Grappler"
          }
        ],
        "conditions": [
          {
            "index": "blinded",
            "name": "Blinded"
          },
          {
            "index": "charmed",
            "name": "Charmed"
          },
          {
            "index": "deafened",
            "name": "Deafened"
          },
          {
            "index": "frightened",
            "name": "Frightened"
          },
          {
            "index": "grappled",
            "name": "Grappled"
          },
          {
            "index": "incapacitated",
            "name": "Incapacitated"
          },
          {
            "index": "invisible",
            "name": "Invisible"
          },
          {
            "index": "paralyzed",
            "name": "Paralyzed"
          },
          {
            "index": "petrified",
            "name": "Petrified"
          },
          {
            "index": "poisoned",
            "name": "Poisoned"
          },
          {
            "index": "prone",
            "name": "Prone"
          },
          {
            "index": "restrained",
            "name": "Restrained"
          },
          {
            "index": "stunned",
            "name": "Stunned"
          },
          {
            "index": "unconscious",
            "name": "Unconscious"
          },
          {
            "index": "exhaustion",
            "name": "Exhaustion"
          }
        ],
        "creatureTypes": [
          "aberration",
          "beast",
          "celestial",
          "construct",
          "dragon",
          "elemental",
          "fey",
          "fiend",
          "giant",
          "humanoid",
          "monstrosity",
          "ooze",
          "plant",
          "undead"
        ],
        "sizes": [
          "Tiny",
          "Small",
          "Medium",
          "Large",
          "Huge",
          "Gargantuan"
        ]
      }
    }
  },
  "characters": [
    {
      "id": "hane",
      "schemaVersion": 1,
      "ruleset": "dnd5e-2014",
      "kind": "monster",
      "name": "Hané Pathfinder",
      "size": "Medium",
      "type": "Wind-Kin (Path-Keeper)",
      "alignment": "Neutral",
      "flavour": "Hané Pathfinders are wise keepers of the wind-paths…",
      "ac": "15 (aerial awareness)",
      "hp": "110 (13d8 + 52)",
      "speed": "10 ft., fly 70 ft. (hover)",
      "abilities": {
        "STR": 10,
        "DEX": 18,
        "CON": 18,
        "INT": 14,
        "WIS": 20,
        "CHA": 16
      },
      "saves": "Dex +8, Wis +9",
      "skills": "Perception +9, Insight +9, Survival +9, Acrobatics +8",
      "resist": "psychic; bludgeoning from non-magical attacks while airborne",
      "condImm": "prone (while flying), disoriented",
      "senses": "passive Perception 19",
      "languages": "Auran, Common, Wind-Sign",
      "challenge": "9 (5,000 XP)",
      "traits": [
        {
          "name": "Path Stability (Aura)",
          "text": "Within 60 feet…"
        }
      ],
      "actions": [
        {
          "name": "Multiattack",
          "text": "The Pathfinder makes two Talon Strikes."
        }
      ],
      "reactions": [
        {
          "name": "Course Correction",
          "text": "When a creature within 30 feet…"
        }
      ],
      "dump": "A wise falcon-person who keeps the wind-paths…",
      "art": {
        "appearance": "Anthropomorphic falcon, slate-grey and cream plumage, amber eyes",
        "outfit": "Layered blue travelling robes, rope belts",
        "pose": "Hovering, wings spread",
        "environment": "Above misty island peaks, soft daylight",
        "personality": "Calm, watchful, never still",
        "style": "Painterly high fantasy, soft natural light"
      },
      "portraits": {
        "at-rest": {
          "prompt": "…",
          "imageUrl": null,
          "seed": null
        },
        "in-conversation": {
          "prompt": "…",
          "imageUrl": null,
          "seed": null
        },
        "in-battle": {
          "prompt": "…",
          "imageUrl": null,
          "seed": null
        },
        "travelling": {
          "prompt": "…",
          "imageUrl": null,
          "seed": null
        }
      }
    },
    {
      "id": "lyra-emberquill",
      "schemaVersion": 1,
      "ruleset": "dnd5e-2014",
      "kind": "character",
      "name": "Lyra Emberquill",
      "size": "Medium",
      "type": "humanoid (elf)",
      "alignment": "Chaotic Good",
      "flavour": "A high-elf evoker who chases forbidden fire-lore through every ruin she can find.",
      "ac": "12 (mage armor)",
      "hp": "32 (5d6 + 10)",
      "speed": "30 ft.",
      "abilities": {
        "STR": 8,
        "DEX": 14,
        "CON": 14,
        "INT": 17,
        "WIS": 12,
        "CHA": 10
      },
      "saveProfs": [
        "INT",
        "WIS"
      ],
      "skillProfs": [
        {
          "skill": "Arcana",
          "expertise": false
        },
        {
          "skill": "Investigation",
          "expertise": false
        },
        {
          "skill": "History",
          "expertise": false
        }
      ],
      "saves": "Int +6, Wis +4",
      "skills": "Arcana +6, Investigation +6, History +6",
      "senses": "passive Perception 11",
      "languages": "Common, Elvish, Draconic",
      "challenge": "— (level 5)",
      "traits": [
        {
          "name": "Arcane Recovery",
          "text": "Once per day on a short rest, recover spell slots totalling up to half your wizard level (rounded up).",
          "source": "class:Wizard"
        },
        {
          "name": "Fey Ancestry",
          "text": "Advantage on saves against being charmed; magic can't put you to sleep.",
          "source": "race:Elf"
        },
        {
          "name": "Researcher",
          "text": "When you try to learn or recall a piece of lore, you often know where to find it.",
          "source": "background:Sage"
        }
      ],
      "actions": [
        {
          "name": "Quarterstaff",
          "text": "Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 3 (1d6) bludgeoning damage."
        },
        {
          "name": "Fire Bolt (cantrip)",
          "text": "Ranged Spell Attack: +6 to hit, range 120 ft., one target. Hit: 11 (2d10) fire damage."
        }
      ],
      "reactions": [
        {
          "name": "Shield (1st-level spell)",
          "text": "When hit by an attack or targeted by magic missile, raise an invisible barrier: +5 AC until the start of your next turn, and no damage from magic missile.",
          "source": "class:Wizard"
        }
      ],
      "dump": "A driven high-elf evoker, ink-stained and singed, who can't resist a locked archive.",
      "art": {
        "appearance": "Slender high elf with ash-blonde hair tied back, faint burn-scars on her fingertips, sharp amber eyes",
        "outfit": "Travel-worn indigo robes with rolled sleeves, a bandolier of chalk and reagents, a satchel of scrolls",
        "pose": "One hand wreathed in a small controlled flame, the other holding an open spellbook",
        "environment": "A candlelit ruined library, shelves leaning, dust hanging in the light",
        "personality": "Curious, impatient, quietly reckless",
        "style": "Painterly high fantasy, warm candlelight against deep shadow"
      },
      "portraits": {
        "at-rest": {
          "prompt": null,
          "imageUrl": null,
          "seed": null
        },
        "in-conversation": {
          "prompt": null,
          "imageUrl": null,
          "seed": null
        },
        "in-battle": {
          "prompt": null,
          "imageUrl": null,
          "seed": null
        },
        "travelling": {
          "prompt": null,
          "imageUrl": null,
          "seed": null
        }
      },
      "pc": {
        "species": "elf",
        "subspecies": "high-elf",
        "class": "wizard",
        "subclass": "evocation",
        "level": 5,
        "background": "sage",
        "abilityMethod": "point_buy",
        "hitDice": {
          "die": "d6",
          "total": 5,
          "remaining": 5
        },
        "deathSaves": {
          "successes": 0,
          "failures": 0
        },
        "proficiencies": {
          "armor": [],
          "weapons": [
            "daggers",
            "darts",
            "slings",
            "quarterstaffs",
            "light crossbows"
          ],
          "tools": []
        },
        "feats": [],
        "equipment": [
          {
            "name": "Spellbook"
          },
          {
            "name": "Quarterstaff"
          },
          {
            "name": "Component pouch"
          },
          {
            "name": "Scholar's pack"
          },
          {
            "name": "Potion of healing",
            "qty": 2
          }
        ],
        "currency": {
          "cp": 0,
          "sp": 0,
          "ep": 0,
          "gp": 25,
          "pp": 0
        },
        "personality": {
          "traits": [
            "Quotes obscure texts mid-conversation"
          ],
          "ideals": [
            "Knowledge — the path to power and self-improvement"
          ],
          "bonds": [
            "My spellbook is my life's work; I would burn for it"
          ],
          "flaws": [
            "I overlook the obvious while chasing the arcane"
          ]
        }
      },
      "spellcasting": {
        "ability": "int",
        "saveDc": 14,
        "attackBonus": 6,
        "slots": {
          "1": {
            "total": 4,
            "expended": 0
          },
          "2": {
            "total": 3,
            "expended": 0
          },
          "3": {
            "total": 2,
            "expended": 0
          }
        },
        "cantrips": [
          "fire-bolt",
          "mage-hand",
          "prestidigitation",
          "light"
        ],
        "prepared": [
          "magic-missile",
          "shield",
          "misty-step",
          "scorching-ray",
          "fireball"
        ]
      }
    },
    {
      "ruleset": "dnd5e-2014",
      "kind": "npc",
      "name": "Brakkin Ironeye",
      "size": "Medium",
      "type": "humanoid (dwarf)",
      "alignment": "neutral good",
      "flavour": "A one-eyed dwarf blacksmith who traded the forge for the hunt, his rune-etched warhammer humming whenever the dead walk near.",
      "ac": "17 (chain mail)",
      "hp": "104 (16d8 + 32)",
      "speed": "25 ft.",
      "abilities": {
        "STR": 17,
        "DEX": 11,
        "CON": 15,
        "INT": 12,
        "WIS": 14,
        "CHA": 10
      },
      "saveProfs": [
        "STR",
        "CON"
      ],
      "skillProfs": [
        {
          "skill": "Athletics",
          "expertise": false
        },
        {
          "skill": "Perception",
          "expertise": false
        },
        {
          "skill": "Survival",
          "expertise": true
        }
      ],
      "resist": "poison",
      "condImm": "",
      "languages": "Common, Dwarvish",
      "challenge": "5 (1,800 XP)",
      "traits": [
        {
          "name": "Dwarven Resilience",
          "text": "Brakkin has advantage on saving throws against poison."
        },
        {
          "name": "Monster Hunter's Lore",
          "text": "Brakkin has advantage on Intelligence and Wisdom checks made to recall information about aberrations, fiends, and undead, and to identify their weaknesses."
        },
        {
          "name": "Tough as Old Boots",
          "text": "When Brakkin is reduced to 0 hit points but not killed outright, he can drop to 1 hit point instead. He can use this trait once and regains its use after a long rest."
        }
      ],
      "actions": [
        {
          "name": "Multiattack",
          "text": "Brakkin makes two attacks with his rune-etched warhammer."
        },
        {
          "name": "Rune-Etched Warhammer",
          "text": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (1d8 + 3) bludgeoning damage, or 11 (1d10 + 3) bludgeoning damage if used with two hands. If the target is undead, it takes an extra 7 (2d6) radiant damage and must succeed on a DC 14 Constitution saving throw or be unable to take reactions until the start of Brakkin's next turn."
        },
        {
          "name": "Throwing Hammer",
          "text": "Ranged Weapon Attack: +6 to hit, range 20/60 ft., one target. Hit: 7 (1d6 + 3) bludgeoning damage."
        },
        {
          "name": "Hunter's Mark (1/Day)",
          "text": "Brakkin marks one creature he can see within 90 feet. Once per turn, his first hit against that creature deals an extra 3 (1d6) damage. The mark lasts for 1 hour or until the target drops to 0 hit points."
        }
      ],
      "reactions": [
        {
          "name": "Forgewarden's Guard",
          "text": "When a creature Brakkin can see within 5 feet of him hits an ally with an attack, Brakkin imposes disadvantage on that attack roll."
        }
      ],
      "dump": "A grizzled, one-eyed dwarf blacksmith turned monster-hunter with a rune-etched warhammer that hums near the undead; gruff but secretly kind, fond of ale, walking with an old limp.",
      "art": {
        "appearance": "Stocky weathered dwarf with a thick iron-grey braided beard, a milky scarred socket where one eye should be, and broad calloused blacksmith's hands",
        "outfit": "Soot-stained leather apron over dented chain mail, a tankard hooked to his belt, a brace of throwing hammers across his chest",
        "pose": "Leaning on his glowing rune-etched warhammer, weight off one stiff leg, scanning the dark with his good eye",
        "environment": "A dim forge-lit smithy at the edge of a haunted moor, anvil cold and hammer ready",
        "personality": "Gruff and blunt, hiding a warm protective heart beneath the grumbling and ale",
        "style": "Gritty painterly dark fantasy, warm forge light against cold shadow"
      },
      "schemaVersion": 1,
      "id": "brakkin-ironeye",
      "saves": "Str +6, Con +5",
      "skills": "Athletics +6, Perception +5, Survival +8",
      "senses": "passive Perception 15",
      "portraits": {
        "at-rest": {
          "prompt": null,
          "imageUrl": null,
          "seed": null
        },
        "in-conversation": {
          "prompt": null,
          "imageUrl": null,
          "seed": null
        },
        "in-battle": {
          "prompt": null,
          "imageUrl": null,
          "seed": null
        },
        "travelling": {
          "prompt": null,
          "imageUrl": null,
          "seed": null
        }
      }
    }
  ]
};
